---
title: "NE Abundance"
author: "Jordyn Stoll"
date: "September 2, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
NEab <- read.csv("~/Documents/GitHub/algalanalysis/algalcommunityanalysis/Community Analysis/NE abundance.csv")
str(NEab)
summary(NEab)

```


```{r}
library(plyr)
##how to remove the ggplot legend https://stackoverflow.com/questions/35618260/remove-legend-ggplot-2-2
##How to remove Na's https://stackoverflow.com/questions/17216358/eliminating-nas-from-a-ggplot


NEab$Treatment <- factor(NEab$Treatment,levels=c("Initial","Control","Nitrogen","Phosphorus", "Trace","N+P","N+Trace","P+Trace","N+P+Trace"))
NEab.sub <- NEab[!is.na(NEab)]
summarystatsMicro<- ddply(NEab, "Treatment", summarize,
                     Microcystis.spp..mean=mean(Microcystis.spp.),
                     Microcystis.spp..sd=sd(Microcystis.spp.),
                     Microcystis.spp..se=sd(Microcystis.spp.)/sqrt(length(Microcystis.spp.)))
library(ggplot2)
Microsummaryplot<-ggplot(summarystatsMicro,aes(Treatment, Microcystis.spp..mean, fill=Treatment))+ 
  geom_bar(stat='identity',color='black')+
  geom_errorbar(aes(ymin=Microcystis.spp..mean-Microcystis.spp..se, ymax=Microcystis.spp..mean+Microcystis.spp..se))+
  theme(axis.text.x=element_text(angle = 45, hjust=1))+
  ggtitle("North Erie Microcystis spp. % Abundance")

Microsummaryplot

```