---
title: "SFS2018_plots"
author: "Dave Costello"
date: "5/16/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

##Setup
###Data entry
```{r}
###INC DATA
inc <- read.csv("HAB2017_incub.csv")

#Cut out Chelex and resort
inc2 <- subset(inc,Treatment!="Chelex")
inc2$Treatment <- inc2$Treatment[drop=T,]
inc2$Treatment <- factor(inc2$Treatment,levels=c("Initial","Control","NH4","PO4","N+P","Trace","N+trace","P+trace","N+P+trace"))
inc2$Site <- factor(inc2$Site,levels=c("NErie","Maumee","Ford","GB"))

#MC data
MC <- read.csv("incub_MC.csv")
MCag <- aggregate(MC$MC,by=list(MC$Treatment,MC$Site),mean)
colnames(MCag)[3]<-"MC"

#Merge data
inc2$TS <- paste(inc2$Site,inc2$Treatment)
MCag$TS <- paste(MCag$Group.2,MCag$Group.1)
inc3 <- merge(inc2,MCag[,3:4],by="TS")

#Site subsets
NEr.plot <- subset(inc3,inc3$Site=="NErie")
Mau.plot <- subset(inc3,inc3$Site=="Maumee")

###NDS DATA
NDS <- read.csv(file="NDS_chla.csv")
NDS$TRT <- factor(NDS$TRT,levels=c("Control","NH4","PO4","N&P","Fe","Zn","Ni&Mo",
                                   "N&Zn","N&Fe","P&Ni&Mo"))

MC <- read.csv(file="NDS_MC.csv")
MC$TRT <- factor(MC$TRT,levels=c("Control","NH4","PO4","N&P","Fe","Zn","Ni&Mo",
                                   "N&Zn","N&Fe","P&Ni&Mo"))

#MC units are Âµg/disk. To convert to ug/m2 divide by 3.8 (cm2 of disk) and multiply by 10,000 (cm2/m2)
MC$MCarea <- MC$MC*(10000/3.8)

#Separate by sites
NE1.plot <- subset(NDS,SITE=="N ERIE 1")
NE1.MC <- subset(MC,SITE=="N. ERIE 1")
MAU.plot <- subset(NDS,SITE=="MAUMEE 1"|SITE=="MAUMEE 2")
MAU.MC <- subset(MC,SITE=="MAUMEE 1"|SITE=="MAUMEE 2")

#DL CALCS
#Mean vol = 50 mL x 0.1 ug/L x (10000/3.8) = 13 ug/m2
```

###Site maps

```{r site maps}
library(maps)
library(mapdata)
lkNDS <- read.csv(file="lakeNDSsites.csv")

#BIG MAP
png(file="fullmap.png",height=4,width=4,units="in",res=200)
#pdf(file="fullmap.pdf",height=4,width=4)

map("worldHires","US",xlim=c(-89,-81),ylim=c(41,47),col="white")
map("state",c("michigan","ohio","indiana","pennsylvania","illinois","west virginia","wisconsin"),add=T,col="grey90",fill=T)
map("worldHires","Canada",add=T,col="grey90",fill=T)
rect(-83.7,41.2,-82.2,42.2,lwd=1.2,border="red")
rect(-88.3,44.4,-86.5,45.9,lwd=1.2,border="red")
text(-83.7,42.2,labels="6",adj=c(-0.5,1.5),col="red",cex=0.5)
text(-88.3,45.9,labels="4",adj=c(-5,1.5),col="red",cex=0.5)
points(lkNDS$Long,lkNDS$Lat,cex=0.5,pch=16,col="red")
box()

dev.off()

#LAKE ERIE MAP
png(file="OHmap.png",height=4,width=4,units="in",res=200)
#pdf(file="OHmap.pdf",height=4,width=4)

map("state","ohio",xlim=c(-83.7,-82.2),ylim=c(41.2,42.2),col="grey90",fill=T)
map("state","michigan",xlim=c(-86,-80),ylim=c(40,45),add=T,col="grey90",fill=T)
map("worldHires","Canada",xlim=c(-86,-80),ylim=c(40,45),add=T,col="grey90",fill=T)
box()
points(lkNDS$Long,lkNDS$Lat,cex=1,col="red")
points(Lat~Long,data=lkNDS[lkNDS$Incub==T,],pch=16,col="red",cex=1)
points(Lat~Long,data=lkNDS[lkNDS$Incub==T,],pch=1,col="black",cex=1)

#State names
text(-83.2,41.5,"OHIO")
text(-83.45,42.05,"MICHIGAN")
text(-82.7,42.1,"ONTARIO")

#Site names
text(-82.6,41.5,"Sandusky",cex=0.5)
text(-83.3,41.75,"Maumee",cex=0.5)
text(-83.1,41.9,"N. Erie",cex=0.5)
text(-82.35,41.35,"Old Woman",cex=0.5)

dev.off()

#LAKE MICHIGAN MAP
png(file="WImap.png",height=4,width=4,units="in",res=200)
#pdf(file="WImap.pdf",height=4,width=3.5)

map("state","wisconsin",xlim=c(-88.3,-86.5),ylim=c(44.4,45.9),col="grey90",fill=T)
map("state","michigan",xlim=c(-88.3,-86.5),ylim=c(44.4,45.9),col="grey90",fill=T,add=T)
box()

points(lkNDS$Long,lkNDS$Lat,cex=1,col="red")
points(Lat~Long,data=lkNDS[lkNDS$Incub==T,],pch=16,col="red",cex=1)
points(Lat~Long,data=lkNDS[lkNDS$Incub==T,],pch=1,col="black",cex=1)

#State names
text(-87.5,45.8,"MICHIGAN")
text(-88,45,"WISC.")

#Site names
text(-87.9,44.7,"Green Bay/Fox",cex=0.5)
text(-87.0,45.65,"Ford",cex=0.5)

dev.off()
```

##Nutrient limitation plots
##All sites background CHLA
```{r}
pdf(file="IncBack.pdf",height=6,width=4)
plot(Chla*1000~Site,data=inc3[inc3$Treatment=="Control",],las=2,ylab="Chlorophyll a (Âµg/L)",xlab="",ylim=c(0,200))
dev.off()
```

###N. Erie plots
```{r North Erie incubator}
pdf("NEr_inc.pdf",height=4.2,width=6)
par(mai=c(1,1,0.2,1))

#par(pin=c(4,3))
plot(Chla*1000~Treatment,data=NEr.plot,las=2,xlab="",ylim=c(0,120),ylab="Chlorophyll a (Âµg/L)")
points(MC*60~as.numeric(Treatment),data=NEr.plot,cex=2,col="red",lwd=2,pch=18)
axis(4,las=2,labels=seq(0,2,by=0.4),at=seq(0,120,by=24),col="red",col.axis="red")
mtext("Microcystin (Âµg/L)",4,line=2.5,col="red")
abline(h=0.1*60,col="red",lty=2)

dev.off()
```

```{r North Erie NDS}
png("NEr_NDS.png",height=4.2,width=6,units="in",res=200)
#pdf("NEr_NDS.pdf",height=4.2,width=6)
par(mai=c(1,1,0.2,1))

#par(pin=c(4,3))
plot(CHLA~TRT,data=NE1.plot,las=2,xlab="",ylim=c(0,120),ylab=expression("Chlorophyll a (mg/m"^2*")"))
points(MCarea~as.numeric(TRT),data=NE1.MC,cex=2,col="red",lwd=2,pch=18)
axis(4,las=2,col="red",col.axis="red")
mtext(expression("Microcystin (µg/m"^2*")"),4,line=2.5,col="red")
abline(h=13,col="red",lty=2)

dev.off()
```

###Maumee
```{r Maumee incubator}
#png("MAU_inc_noMC.png",height=4.2,width=6,units="in",res=200)
#pdf("MAU_inc.pdf",height=4.2,width=6)
png("MAU_inc.png",height=4.2,width=6,units="in",res=200)

par(mai=c(1,1,0.2,1))

#par(pin=c(4,3))
plot(Chla*1000~Treatment,data=Mau.plot,las=2,xlab="",ylim=c(0,250),ylab="Chlorophyll a (µg/L)")
points(MC*20~as.numeric(Treatment),data=Mau.plot,cex=2,col="red",lwd=2,pch=18)
axis(4,las=2,labels=seq(0,10,by=2),at=seq(0,250,by=50),col="red",col.axis="red")
mtext("Microcystin (µg/L)",4,line=2.5,col="red")
abline(h=0.1*60,col="red",lty=2)

dev.off()
```

```{r Mau NDS}
#pdf("MAU_NDS_noMC.pdf",height=4.2,width=6)
#pdf("MAU_NDS.pdf",height=4.2,width=6)
#png("MAU_NDS_noMC.png",height=4.2,width=6,units="in",res=200)
png("MAU_NDS.png",height=4.2,width=6,units="in",res=200)
par(mai=c(1,1,0.2,1))

#par(pin=c(4,3))
plot(CHLA~TRT,data=MAU.plot,las=2,xlab="",ylim=c(0,300),ylab=expression("Chlorophyll a (mg/m"^2*")"))
points(MCarea~as.numeric(TRT),data=MAU.MC,cex=2,col="red",lwd=2,pch=18)
axis(4,las=2,col="red",col.axis="red")
mtext(expression("Microcystin (µg/m"^2*")"),4,line=2.5,col="red")
abline(h=13,col="red",lty=2)

dev.off()
```