---
title: "Biostats Project"
author: "Jordyn Stoll"
date: "April 24, 2018-"
output: html_document
---
Go back to the ANOVA and find the Tukey tst for the higest order interaction and label bars accoding to that
--NE will be tricky to distinguish between the two types of limitation
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Documents/GitHub/algalanalysis/AFDM:ChlA/Biomass Analysis/")
Compiled.Meso.Data <-read.csv("~/Documents/GitHub/algalanalysis/AFDM:ChlA/Compiled Meso Data.csv")
summary(Compiled.Meso.Data)
str(Compiled.Meso.Data)
#remove chelex and intial treatments
simplified<-Compiled.Meso.Data[which(Compiled.Meso.Data$treatment!='chelex'& Compiled.Meso.Data$treatment!='initial'),]
#order treatments in a logical way
simplified$treatment <- factor(simplified$treatment,levels=c("control","nitrogen","phosphorus","trace","n+p","n+trace","p+trace","n+p+trace"))

#subset each site by finding the 'string' in the sample ID
ford1<-subset(simplified,grepl('Ford', simplified$sampleID))
greenbay1<-subset(simplified,grepl('GB',simplified$sampleID))
nerie1<-subset(simplified, grepl('NE',simplified$sampleID))
maumee1<-subset(simplified,grepl('Maumee',simplified$sampleID))
```
##FORD
```{r}
#AFDM MANOVA
fordAFDMman<-aov(AFDM~nitrogen*phosphorus*trace, data=ford1)
shapiro.test(resid(fordAFDMman))
par(mfrow=c(1,2))
plot(fordAFDMman,which=c(1,2), main="Ford Normality")
summary(fordAFDMman)
##trace and p significant
#create plot to demonstrate AFDM~Treatment
par(mfrow=c(1,1))
ford1$treatment<-ford1$treatment[,drop=T]
plot(AFDM~treatment,data=ford1,
     main="Treatment Effect on AFDM: Ford River",
     ylab="AFDM (mg/L)",
     xlab="Treatment", xaxt="n",
     col=c("gray76","gray76","gray76","gray76","gray76","gray76","darkturquoise","darkturquoise"))
text(ford1$treatment,labels=c("control","nitrogen","phosphorus","trace","n+p","n+trace","p+trace","n+p+trace"),adj=,srt=45)


mtext(c("control","nitrogen","phosphorus","trace","n+p","n+trace","p+trace","n+p+trace"),side=1,line=1,at=c(1:8),srt=45)

legend("topleft", bty="n", legend=c("ANOVA p <0.05","ANOVA p >0.05"),fill=c("darkturquoise","gray76"), cex=0.8)
```
#GREENBAY
```{r}
#AFDM MANOVA
gbAFDMman<-aov(AFDM~nitrogen*phosphorus*trace, data=greenbay1)
shapiro.test(resid(gbAFDMman))
par(mfrow=c(1,2))
plot(gbAFDMman,which=c(1,2),main="Green Bay Normality")
summary(gbAFDMman)
#p:n significant, p and p:trace almost significant 
#create plot to demonstrate AFDM~Treatment
par(mfrow=c(1,1))
greenbay1$treatment<-greenbay1$treatment[,drop=T]
plot(AFDM~treatment,data=greenbay1,
     main="Treatment Effect on AFDM: Green Bay",
     ylab="AFDM (mg/L)",
     xlab="", las=2,
     col=c("gray76","darkturquoise","gray76","gray76","darkturquoise","gray76","gray76","gray76"))
legend("topleft", bty="n", legend=c("ANOVA p <0.05","ANOVA p >0.05"),fill=c("darkturquoise","gray76"), cex=0.8)

boxplot(AFDM~nitrogen*phosphorus, data=greenbay1, main="Green Bay N & P effect on AFDM", xlab="Treatment Nitrogen*Phosphorus",ylab="AFDM mg/L")
```
##NORTH ERIE
```{r}
#AFDM MANOVA
neAFDMman<-aov(AFDM~nitrogen*phosphorus*trace, data=nerie1)
shapiro.test(resid(neAFDMman))
par(mfrow=c(1,2))
plot(neAFDMman,which=c(1,2),main="North Erie Normality")
summary(neAFDMman)
#p, trace, n:p, p:trace significant 
#create plot to demonstrate AFDM~Treatment
par(mfrow=c(1,1))
nerie1$treatment<-nerie1$treatment[,drop=T]
plot(AFDM~treatment,data=nerie1,
     main="Treatment Effect on AFDM: North Erie",
     ylab="AFDM (mg/L)",
     xlab="", las=2,
     col=c("gray76","darkturquoise","gray76","gray76","gray76","darkturquoise","darkturquoise","darkturquoise"))
legend("topleft", bty="n", legend=c("ANOVA p <0.05","ANOVA p >0.05"),fill=c("darkturquoise","gray76"), cex=0.8)
```
##MAUMEE
```{r}
#AFDM MANOVA
mAFDMman<-aov(AFDM~nitrogen*phosphorus*trace, data=maumee1)
shapiro.test(resid(mAFDMman))
par(mfrow=c(1,2))
plot(mAFDMman,which=c(1,2),main="Maumee Normality")
summary(mAFDMman)
TukeyHSD(mAFDMman)
#p, p:trace significant
#create plot to demonstrate AFDM~Treatment
par(mfrow=c(1,1))
maumee1$treatment<-maumee1$treatment[,drop=T]
plot(AFDM~treatment,data=maumee1,
     main="Treatment Effect on AFDM: Maumee River",
     ylab="AFDM (mg/L)",
     xlab="", las=2,
     col=c("gray76","gray76","gray76","gray76","gray76","darkturquoise","darkturquoise","gray76"))
legend("topleft", bty="n", legend=c("ANOVA p <0.05","ANOVA p >0.05"),fill=c("darkturquoise","gray76"), cex=0.8)

boxplot(AFDM~phosphorus*trace, data=maumee1, main="Maumee P & Trace effect on AFDM", ylab="AFDM (mg/L)", xlab="Treatment Phosphorus*Trace metals")

```

Start Chla Analysis
##FORD
```{r}
#Chla MANOVA
fordChlAman<-aov(ChlA~nitrogen*phosphorus*trace, data=ford1)
shapiro.test(resid(fordChlAman))
par(mfrow=c(1,2))
plot(fordChlAman,which=c(1,2), main="Ford Normality")
summary(fordChlAman)
##NEEDS TRANSFORMED
ford1$logchla<-log(ford1$ChlA)
fordChlAman2<-aov(logchla~nitrogen*phosphorus*trace, data=ford1)
shapiro.test(resid(fordChlAman2))
par(mfrow=c(1,2))
plot(fordChlAman2,which=c(1,2), main="Ford Normality")
summary(fordChlAman2)
#P significant
#create plot to demonstrate ChlA~Treatment
par(mfrow=c(1,1))
ford1$treatment<-ford1$treatment[,drop=T]
plot(logchla~treatment,data=ford1,
     main="Treatment Effect on ChlA: Ford River",
     ylab="ChlA (mg/L)",
     xlab="Treatment", las=2,
     col=c("gray76","gray76","darkturquoise","gray76","gray76","gray76","gray76","gray76"))
legend("topleft", bty="n", legend=c("ANOVA p <0.05","ANOVA p >0.05"),fill=c("darkturquoise","gray76"), cex=0.8)
```
#GREENBAY
```{r}
#CHLA MANOVA
gbCHLAman<-aov(ChlA~nitrogen*phosphorus*trace, data=greenbay1)
shapiro.test(resid(gbCHLAman))
par(mfrow=c(1,2))
plot(gbCHLAman,which=c(1,2),main="Green Bay Normality")
summary(gbCHLAman)
TukeyHSD(gbCHLAman)
#nitrogen and p+trace significant
#create plot to demonstrate Chla~Treatment
par(mfrow=c(1,1))
greenbay1$treatment<-greenbay1$treatment[,drop=T]
plot(ChlA~treatment,data=greenbay1,
     main="Treatment Effect on Chla: Green Bay",
     ylab="Chla (mg/L)",
     xlab="", las=2,
     col=c("gray76","darkturquoise","gray76","gray76","gray76","gray76","darkturquoise","gray76"))
legend("topleft", bty="n", legend=c("ANOVA p <0.05","ANOVA p >0.05"),fill=c("darkturquoise","gray76"), cex=0.8)

boxplot(Chla~nitrogen*phosphorus, data=greenbay1, main="Green Bay N & P effect on Chla", xlab="Treatment Nitrogen*Phosphorus",ylab="Chla mg/L")
```
##NORTH ERIE-NEEDS TRANSFORMED-fix colors
```{r}
#CHLA MANOVA
neChlAman<-aov(ChlA~nitrogen*phosphorus*trace, data=nerie1)
shapiro.test(resid(neChlAman))
par(mfrow=c(1,2))
plot(neChlAman,which=c(1,2),main="North Erie Normality")
summary(neChlAman)
#LOG TRANSFORMATION
nerie1$logchla<-log(nerie1$ChlA)
nerieChlAman2<-aov(logchla~nitrogen*phosphorus*trace, data=nerie1)
shapiro.test(resid(nerieChlAman2))
par(mfrow=c(1,2))
plot(nerieChlAman2,which=c(1,2), main="NErie Normality")
summary(nerieChlAman2)
#P, significant, N:P close
###STILL NOT NORMAL
#remove outlier bottles 9 and 22 (lower than expected mean for treatmen)
nerie2<- nerie1[-c(9,22), ]
nerie2$logchla<-log(nerie2$ChlA)
nerieChlAman3<-aov(logchla~nitrogen*phosphorus*trace, data=nerie2)
shapiro.test(resid(nerieChlAman3))
par(mfrow=c(1,2))
plot(nerieChlAman3,which=c(1,2), main="NErie Normality")
summary(nerieChlAman3)
#P significant
#create plot to demonstrate AFDM~Treatment
par(mfrow=c(1,1))
nerie2$treatment<-nerie2$treatment[,drop=T]
plot(AFDM~treatment,data=nerie2,
     main="Treatment Effect on AFDM: North Erie",
     ylab="AFDM (mg/L)",
     xlab="", las=2,
     col=c("gray76","gray76","darkturquoise","gray76","gray76","gray76","gray76","gray76"))
legend("topleft", bty="n", legend=c("ANOVA p <0.05","ANOVA p >0.05"),fill=c("darkturquoise","gray76"), cex=0.8)
```
##MAUMEE
```{r}
#CHLA MANOVA
mChlAman<-aov(ChlA~nitrogen*phosphorus*trace, data=maumee1)
shapiro.test(resid(mChlAman))
par(mfrow=c(1,2))
plot(mChlAman,which=c(1,2),main="Maumee Normality")
summary(mChlAman)
TukeyHSD(mChlAman)
#n, p
#create plot to demonstrate AFDM~Treatment
par(mfrow=c(1,1))
maumee1$treatment<-maumee1$treatment[,drop=T]
plot(ChlA~treatment,data=maumee1,
     main="Treatment Effect on ChlA: Maumee River",
     ylab="ChlA (mg/L)",
     xlab="", las=2,
     col=c("darkturquoise","darkturquoise","gray76","gray76","gray76","gray76","gray76","gray76"))
legend("topleft", bty="n", legend=c("ANOVA p <0.05","ANOVA p >0.05"),fill=c("darkturquoise","gray76"), cex=0.8)

boxplot(AFDM~phosphorus*trace, data=maumee1, main="Maumee P & Trace effect on AFDM", ylab="AFDM (mg/L)", xlab="Treatment Phosphorus*Trace metals")

```
SITE MAPS-discuss with Dave
```{r}
#GOAL: to make a map of Lake Erie/Lake Michigan area with 4 sites plotted
library(maps)
library(mapdata)
#Where does this file come from? What is it's purpose?
lkNDS <- read.csv(file="lakeNDSsites.csv")
#BIG MAP FROM DAVE's CODE
pdf(file="fullmap.pdf",height=4,width=4)
map("worldHires","US",xlim=c(-89,-81),ylim=c(41,47),col="white")
map("state",c("michigan","ohio","indiana","pennsylvania","illinois","west virginia","wisconsin"),add=T,col="grey90",fill=T)
map("worldHires","Canada",add=T,col="grey90",fill=T)
rect(-83.7,41.2,-82.2,42.2,lwd=1.2,border="red")
rect(-88.3,44.4,-86.5,45.9,lwd=1.2,border="red")
text(-83.7,42.2,labels="6",adj=c(-0.5,1.5),col="red",cex=0.5)
text(-88.3,45.9,labels="4",adj=c(-5,1.5),col="red",cex=0.5)
text(-83.3,41.75,"Maumee",cex=0.5)
text(-83.1,41.9,"N. Erie",cex=0.5)
text(-87.9,44.7,"Green Bay",cex=0.5)
text(-87.0,45.65,"Ford",cex=0.5)
points(lkNDS$Long,lkNDS$Lat,cex=0.5,pch=16,col="red")
box()
dev.off()


```
LOG RESPONCE RATIOS
```{r}
#So, how do you do this??
  



```

